services:

  db:
    container_name: pg1
    restart: always
    image: postgres:15.2
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  adminer:
    container_name: adminer1
    image: adminer
    restart: always
    ports:
      - 45010:8080

